### ISSUE TITLE
Add nano to test script

### ISSUE THREAD

**Issue by bsmith89** [sorgerlab/2016-10-06-harvard#13]
On Tue, Oct 4, 2016 at 1:33 PM, James Mickley wrote:

> Byron: Could you add nano as a requirement to the [test script](https://github.com/sorgerlab/2016-10-06-harvard/tree/gh-pages/setup)?  The non-compliance link should point to the [SWC windows installer](https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe).

**Comment by bsmith89** [comment]
@mickley, nano appears to already be in the test script.  Is there something specific that you'd like me to add?

The current link is to http://www.nano-editor.org/dist/latest/faq.html#3.  The link that you suggested is instead linked in the setup instructions.  Is that sufficient?

**Comment by mickley** [comment]
Hmm, It's not in the CHECKS list on line 89.  Perhaps it's built in, but not enabled.  I can test it I suppose.

**Comment by bsmith89** [comment]
Ah!  I see now.  It's a sub-check for 'virtual-editor', but learners can have any editor installed.  I guess we don't really want learners to pass the test with just vim or emacs.
