### ISSUE TITLE
Add parking options under general information

### ISSUE THREAD

**Issue by mickley** [sorgerlab/2016-10-06-harvard#9]
@jmuhlich?  Useful for learners, and also probably for us as well.

**Comment by jmuhlich** [comment]
We'll easily fill the room with internal folks who already work here. If we don't hit 24 registrants from our (large) lab, I'll open it up to other people in the department and surely get to 24. I can send you parking details privately.

**Comment by mickley** [comment]
Thanks Jeremy.  As I've mentioned before, I was hoping to invite some colleagues who work at Harvard (they're situated at the Arnold Arboretum).  So if it doesn't fill, this becomes a bit relevant.  

Also, the eventbrite is listing 39 (40 total?) spots.  Is this in error then?  If so, we should have it capped at 24.  I think there's a waitlist set up if using Eventbrite, though Maneesha would know more.
